### ISSUE TITLE
scientific notation of floats

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/py-mapzen-whosonfirst-geojson#2]
some floats are encoded with scientific notation which causes some libraries (mapnik) to error.

eg. below:

``` javascript
"geom:area":2.789235e-07,

[-6.2e-05,-0.000167]
```

``` bash
$ cat data/1/1.geojson
{
  "id": 1,
  "type": "Feature",
  "properties": {
    "edtf:cessation":"u",
    "edtf:inception":"u",
    "geom:area":2.789235e-07,
    "geom:bbox":"-0.0005,-0.000282,0.000379,0.000309",
    "geom:latitude":3.307914774720177e-06,
    "geom:longitude":1.0113151096985358e-05,
...
65],[-6.2e-05,-0.000167],[-6.6e-05,-0.000165],[-6.7e-05,-0.000153],[-7.2e-05,-0.000153],[-7.2e-05,-0.000158],[-6.8e-05,-0.000161],[-7e-05,-0.000166],[-7e-05,-0.000172],[-7.3e-05,-0.000176]],[[-7e-06,-0.000158],[-7e-06,-0.000163],[1.5e-05,-0.000162],[3.7e-05,-0.000163],[3.7e-05,-0.000159],[-7e-06,-0.000158]]]],"type":"MultiPolygon"}
}
```

`node-mapnik` says: `geojson_datasource: Failed to parse GeoJSON file`

**Comment by thisisaaronland** [comment]
Note to self:

This might also be a thing to account for with Shapely in py-mz-wof-export in which case there are two issues...

https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L262-L270

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/whosonfirst-data/commit/14c502d98182e776850e13d8a3a3a50ed2977b5f

**Comment by thisisaaronland** [comment]
There might some stragglers still but we'll deal with those as they come up...
